name: CI

"on":
  push:
    branches:
      - master
    paths:
      - 'posts/**'

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex    # "ubuntu" is a more generic container
                               # using "pandoc/latex" because of dependencies
                               # used in the specific "build.sh"
    steps:
      - uses: actions/checkout@v2
      - name: creates frontend build
        run:  cd frontend && sh ./frontend/build.sh # some command from your repository that creates
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'build'
          destination-github-username: 'skrimmage'
          destination-repository-name: 'skrimmage.github.io'
          user-email: dannypage@users.noreply.github.com
          target-branch: master
