name: CI

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run:  npm install
      - name: creates frontend build
        run:  sh ./build.sh 
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'frontend/build'
          destination-github-username: 'skrimmage'
          destination-repository-name: 'skrimmage.github.io'
          user-email: dannypage@users.noreply.github.com
          target-branch: master
